export const ADD_ROULETTE_SET = "ADD_ROULETTE_SET";
export const DELETE_ROULETTE_SET = "DELETE_ROULETTE_SET";
export const UPDATE_ROULETTE_RESULT = "UPDATE_ROULETTE_RESULT";
export const OPEN_POPUP = "OPEN_POPUP";
export const CLOSE_POPUP = "CLOSE_POPUP";
