export const ADD_ROULETTE_SET = "ADD_ROULETTE_SET";
export const DELETE_ROULETTE_SET = "DELETE_ROULETTE_SET";
export const DELETE_ALL_ROULETTE_SET = "DELETE_ALL_ROULETTE_SET";
export const UPDATE_ROULETTE_RESULT = "UPDATE_ROULETTE_RESULT";
